### ISSUE TITLE
incompatible with reformatter 20240903.948

### ISSUE THREAD

**Issue by TopSlick** [purcell/sqlformat#14]
Since upgrade of reformatter on melpa to version 20240903.948 , sqlformat-region and sqlformat-buffer are interrupted with message: 
> sqlformat-region/buffer: Wrong number of arguments: #<subr reformatter--do-region>, 10 

Arch Linux, Emacs 29.4, with following customisations
```
 '(sqlformat-args '("--dialect=postgres"))
 '(sqlformat-command 'sqlfluff)

```

**Comment by purcell** [comment]
Ah, that's actually because the `reformatter-define` macro changed in the newer `reformatter` version [recently](https://github.com/purcell/emacs-reformatter/pull/55), so that any users of it (like this package) would need to be recompiled in order to work properly. If you `M-x find-library RET sqlformat RET` and then `M-x byte-recompile-file` that should fix the problem, but I'll also make a change to reformatter so that this shouldn't be necessary.

cc @damiencassou

**Comment by purcell** [comment]
Pushed a `reformatter` update to MELPA — once it is built and you've installed it, this error should go away. Thanks for taking the time to report it.

**Comment by DamienCassou** [comment]
I didn't foresee that, sorry. And thank you @purcell for the quick fix.

**Comment by TopSlick** [comment]
Recompiled package as described and it (indeed) solved the problem. 
Thanks @purcell &  @DamienCassou for your reactivity, pointing to the solution, and implementing the solution to MELPA. Top !

**Comment by purcell** [comment]
> I didn't foresee that, sorry.

Neither did I! It's one of the risks when shipping packages whose public APIs take the form of macros.
